### ISSUE TITLE
TreeEditor Styling

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/coffee-editor#114]
Better functional integration with Theia (Keybindings, Menus, Commands)
Better tree styling (Icons for the tree / moveable Sash)
Better styling integration of JSONForms (LightTheme / DarkTheme)

**Comment by eneufeld** [comment]
@lucas-koehler this should probably be part of the thei-tree-editor repo now?

**Comment by lucas-koehler** [comment]
https://github.com/eclipsesource/theia-tree-editor/issues/11
