### ISSUE TITLE
Run Workflow analysis based on coffee model

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipsesource/coffee-editor#134]
- Change coffee model to use enum in weighted flows
- Adapt analysis component to be compatible with coffee model

**Comment by planger** [comment]
I think, this is fully covered by https://github.com/eclipsesource/coffee-editor/pull/141 isn't it @martin-fleck-at ? If yes, can you please close this? Thanks!

**Comment by martin-fleck-at** [comment]
Yes, that is exactly the change ;-) Thanks!
