### ISSUE TITLE
Tasks with spaces in their names cannot be referenced from wfconfig (Xtext)

### ISSUE THREAD

**Issue by planger** [eclipsesource/coffee-editor#176]
I think we need to change the type of the cross-reference in Xtext as well as the proposal provider to use quotes so that it can handle spaces in task names.

**Comment by eneufeld** [comment]
@planger Who could fix this best? Maybe Martin?

**Comment by planger** [comment]
Yeah, probably. Does it work with quotes? If we use the typical Xtext ID terminal for cross-referencing objects, it should work to put the "name in quotes". If that doesn't work either, we probably need to change the reference type in the grammar.

**Comment by eneufeld** [comment]
Does this mean, I just have to put the keyword in quotes? If so I will try this out.

**Comment by eneufeld** [comment]
Ok, I didn't manage.

**Comment by planger** [comment]
> Does this mean, I just have to put the keyword in quotes? If so I will try this out.

No the reference key should be in quotes (ie the referenced model element name). Does this work?

**Comment by planger** [comment]
But maybe it isn't working here anyway. Depends on the xtext grammar / scoping implementation.

**Comment by eneufeld** [comment]
The task names are retrieved dynamically based on the task names: https://github.com/eclipsesource/coffee-editor/blob/a226476107af75e8a8a08942f8e284f2383329a9/backend/plugins/com.eclipsesource.workflow.dsl.ide/src/com/eclipsesource/workflow/dsl/ide/contentassist/WorkflowIdeContentProposalProvider.xtend#L55
