### ISSUE TITLE
Build error in backend

### ISSUE THREAD

**Issue by koegel** [eclipsesource/coffee-editor#182]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (mwe2Launcher) on project com.eclipsesource.workflow.dsl: Execution mwe2Launcher of goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:1.4.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:1.4.0 -> org.eclipse.emf:org.eclipse.emf.mwe2.launch:jar:2.10.0 -> org.eclipse.emf:org.eclipse.emf.mwe2.runtime:jar:[2.10.0]: No versions available for org.eclipse.emf:org.eclipse.emf.mwe2.runtime:jar:[2.10.0] within specified range -> [Help 1]
[ERROR]

**Comment by eneufeld** [comment]
I cannot reproduce this, can we have a look at this together

**Comment by eneufeld** [comment]
you might need to trigger the build using maven directly and provide the `-U` parameter

**Comment by koegel** [comment]
This resolved the issue
