### ISSUE TITLE
Sometimes connection to model server gets lost

### ISSUE THREAD

**Issue by planger** [eclipsesource/coffee-editor#207]

**Comment by eneufeld** [comment]
@planger was this on the tree or the diagram?

**Comment by planger** [comment]
I think it was on the tree, but I'm not 100 % sure. I think the issue was that at some point the tree doesn't update anymore on changes (e.g. performed via postman).

**Comment by eneufeld** [comment]
I tested the tree in the last days quite extensively, I never had such an issue. I suggest to close this and reopen if we have steps to reproduce. 
@planger what do you think?

**Comment by planger** [comment]
Yeah, sure. If it never happened, I'm fine closing this. We can always re-open if we come across it again.
