### ISSUE TITLE
Remove model server dependencies from theia tree editor

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/coffee-editor#209]
The theia tree editor still has dependencies on the model server. These should be extracted to make the tree usable with different data sources.
Usages of the model server:

- **JsonFormsTreeEditorWidget**
  - `handleFormUpdate` expects a `ModelServerReferenceDescription` as an argument.
  - `getNodeDescription` returns a `ModelServerReferenceDescription`
- **JsonFormsTreeWidget**
  - `addChildren` expects new children as` ModelServerObjects`

**Comment by eneufeld** [comment]
@lucas-koehler is this still the case?

**Comment by lucas-koehler** [comment]
No, this is fixed.
