### ISSUE TITLE
Error during first build

### ISSUE THREAD

**Issue by DamianRivas** [eclipsesource/coffee-editor#290]
```
➜  coffee-editor git:(master) node -v
v10.21.0
➜  coffee-editor git:(master) yarn -v
1.22.4
➜  ~ npm list --installed --global --depth=0 | rg node-gyp
├── node-gyp@7.0.0
➜  coffee-editor git:(master) apt list --installed | rg maven

libmaven-parent-java/focal,focal,now 31-2 all [installed,automatic]
libmaven-resolver-java/focal,focal,now 1.4.1-1 all [installed,automatic]
libmaven-shared-utils-java/focal,focal,now 3.3.0-1 all [installed,automatic]
libmaven3-core-java/focal,focal,now 3.6.3-1 all [installed,automatic]
maven/focal,focal,now 3.6.3-1 all [installed]
➜  coffee-editor git:(master) lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
```

I just cloned the repo and executed the build with `./run.sh`. I got the following error while building the java backend and the coffee editor does not seem to work properly. I think the issues are connected...

![image](https://user-images.githubusercontent.com/10257813/86963790-e8a9b280-c119-11ea-9f5f-562424f2d344.png)

![image](https://user-images.githubusercontent.com/10257813/86963933-2a3a5d80-c11a-11ea-96aa-3c1bb19a028a.png)

![image](https://user-images.githubusercontent.com/10257813/86963986-3e7e5a80-c11a-11ea-9945-53613e246fc8.png)

**Comment by DamianRivas** [comment]
A subsequent, isolated build (with `-b`) also fails

![image](https://user-images.githubusercontent.com/10257813/86965597-a9c92c00-c11c-11ea-8129-d3911ed270c0.png)

**Comment by eneufeld** [comment]
Hi @DamianRivas , 
thank you for your report. 
Could you tell me the java version you are using in with maven?
I just build on my machine and everything works fine. My output of `mvn -version` is:
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
```
Best

**Comment by DamianRivas** [comment]
Hi @eneufeld thank you for looking into this. Here is the output
```
➜  ~ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_252, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-7634-generic", arch: "amd64", family: "unix"
```

I do have Java 11 installed. I modified $JAVA_HOME to point to my installation of Java 11 and the build was successful!

Perhaps that should be stated in: https://github.com/eclipsesource/coffee-editor#prerequisites

Thank you!
