### ISSUE TITLE
Palette was missing on first open of diagram editor

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/coffee-editor#296]
Context menu was working

Palette appeared on second open

Hard to reproduce.

![image](https://user-images.githubusercontent.com/1176277/87049520-5f6bac00-c1fd-11ea-9eb7-17c5a2870539.png)

**Comment by tortmayr** [comment]
Did you debug something on the serverside? The action for requesting the tool palette expects a corresponding respond within a certain threshold. If you have breakpoints on the server it's possible that this respond will timeout

**Comment by eneufeld** [comment]
Closing as not reproducible.
