### ISSUE TITLE
Download plugins should be included in browser-app prepare script 

### ISSUE THREAD

**Issue by kuldeeparora89** [eclipsesource/coffee-editor#302]
After cloning & building the project plugins are not created in browser-app , due to which 3rd party plugins are not getting installed in Theia runtime .

web\browser-app\package.json -
"scripts": {
    "prepare": "theia build --mode development",
Fix-
"scripts": {
    "prepare": "yarn run download:plugins && theia build --mode development",

**Comment by eneufeld** [comment]
Hi @kuldeeparora89, 
good catch. Could you open a PR with the fix please?

**Comment by kuldeeparora89** [comment]
Done
https://github.com/eclipsesource/coffee-editor/pull/303
