### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eclipsesource/coffee-editor#310]
Hello EclipseSource Coffee Editor Example team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

If you are interested that the Coffee Editor Example project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by JonasHelming** [comment]
Sounds cool, thank you for asking!

<tr>
	<td><a href="https://www.eclipse.org/emfcloud/#coffeeeditoroverview">EMF.cloud Coffee Editor</a></td>
	<td>An example web-based modeling tool using EMF.cloud technologies used for demonstration and documentation. Integrates Eclipse Theia, Xtext, Xtend, Eclipse GLSP JSON Forms and the EMF.cloud model server</td>
	<td>EPL 2.0</td>
	<td>Example</td>
	<td>Eugen Neufeld, Lucas Koehler, Martin Fleck, Philip Langer, Stefan Dirix, et al.</td>
</tr>

**Comment by miklossy** [comment]
The `EMF.cloud Coffee Editor` has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
