### ISSUE TITLE
Java files should be compiled before running JUnit

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipsesource/coffee-editor#80]
A resource listener should listen to changes in *.java files and automatically compile the necessary .class files in the 'bin' directory. We need the compiled files to run the JUnit test. Maybe there is already an existing solution.

Currently running JUnit only works if you have an Eclipse open in the background as the Incremental Builder of Eclipse will take care of it.

**Comment by eneufeld** [comment]
so after double checking, it seems that our .project file was incorrect.
Furthermore the jdt-lsp must be started which happens when you open a java file.
Also the full compile only happens on first open after that only incremental compile is done.
